export const STATIONS = [
    {
        id: 'generative',
        name: '✨ 2048 Generative AI',
        description: 'Infinite, realtime Lofi & Jazz generated by your browser.',
        type: 'generative',
        color: '#8e44ad'
    },
    {
        id: 'mfp_76',
        name: 'Music For Programming 76',
        description: 'Material Object',
        type: 'stream',
        url: 'https://datashat.net/music_for_programming_76-material_object.mp3',
        color: '#2c3e50'
    },
    {
        id: 'mfp_75',
        name: 'Music For Programming 75',
        description: 'Datassette',
        type: 'stream',
        url: 'https://datashat.net/music_for_programming_75-datassette.mp3',
        color: '#34495e'
    },
    {
        id: 'mfp_74',
        name: 'Music For Programming 74',
        description: 'NCW',
        type: 'stream',
        url: 'https://datashat.net/music_for_programming_74-ncw.mp3',
        color: '#7f8c8d'
    },
    {
        id: 'mfp_73',
        name: 'Music For Programming 73',
        description: 'Inanace',
        type: 'stream',
        url: 'https://datashat.net/music_for_programming_73-inanace.mp3',
        color: '#95a5a6'
    },
    {
        id: 'mfp_72',
        name: 'Music For Programming 72',
        description: 'Manni Dee',
        type: 'stream',
        url: 'https://datashat.net/music_for_programming_72-manni_dee.mp3',
        color: '#bdc3c7'
    }
];
